# Generated by Django 3.2.16 on 2024-05-09 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0016_alter_job_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.ForeignKey(choices=[('1', 'Executive Leadership'), ('2', 'Management'), ('3', 'Administration and Support'), ('4', 'Sales and Marketing'), ('5', 'Finance and Accounting'), ('6', 'Human Resources'), ('7', 'Information Technology (IT)'), ('8', 'Operations and Logistics'), ('9', 'Legal and Compliance'), ('10', 'Research and Development (R&D)')], on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='jobapp.category'),
        ),
    ]
